import type { ThemeConfig } from '@/types/theme-config';

/**
 * Mock theme configurations for development
 * This will be replaced with real tRPC data in the future
 */
export const mockThemes: Record<string, ThemeConfig> = {
  'acme': {
    colors: {
      primaryText: '#1E2040',
      secondaryText: '#62637A',
      background: '#FFFFFF',
      border: '#E9E9EC',
      primaryGreen: '#03A458',
      secondaryGreen: '#CDEDDE',
      highlight: '#0000FF',
    },
    spacing: {
      micro: '0.25rem',
      xs: '0.5rem',
      sm: '0.75rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2x': '3rem',
      '3x': '4.5rem',
    },
    borders: {
      radius: {
        sm: '0.25rem',
        md: '0.5rem',
        lg: '1rem',
      },
    },
    container: {
      maxWidth: '1100px',
    },
    sections: {
      showProductDetails: true,
      showPrimaryMenu: true,
      showSecondaryMenu: true,
      showImpact: true,
      showMaterials: true,
      showJourney: true,
      showSimilarProducts: true,
      showCTABanner: true,
    },
    images: {
      productImageZoom: 100,
      productImagePosition: 'top',
      carouselImageZoom: 100,
      carouselImagePosition: 'top',
    },
    branding: {
      headerLogoUrl: 'https://res.cloudinary.com/dcdam15xy/image/upload/f_webp/v1746526939/aveleroApparelLogoBlack_iuhow7.png',
      bannerLogoUrl: 'https://res.cloudinary.com/dcdam15xy/image/upload/f_webp/v1746527118/aveleroApparelLogoWhite_b5drvc.png',
      bannerLogoHeight: 40,
    },
    menus: {
      primary: [
        { label: 'Size Guide', url: '#size-guide' },
        { label: 'Care Instructions', url: '#care-instructions' },
      ],
      secondary: [
        { label: 'Sustainability Report', url: '#sustainability' },
        { label: 'Certifications', url: '#certifications' },
        { label: 'Returns & Warranty', url: '#returns' },
      ],
    },
    cta: {
      bannerBackgroundImage: 'https://res.cloudinary.com/dcdam15xy/image/upload/f_auto,q_auto/v1745934275/cta-banner-background_o3vjjw.jpg',
      bannerCTAText: 'DISCOVER MORE',
      bannerCTAUrl: 'https://example.com',
      bannerCTABackgroundColor: '#0000FF',
      bannerCTATextColor: '#FFFFFF',
      bannerShowSubline: false,
      bannerSubline: '',
    },
    social: {
      legalName: 'Acme Studios',
      showInstagram: true,
      showFacebook: true,
      showTwitter: true,
      showPinterest: false,
      showTiktok: false,
      useIcons: true,
      instagramUrl: 'https://instagram.com/acmestudios',
      facebookUrl: 'https://facebook.com/acmestudios',
      twitterUrl: 'https://twitter.com/acmestudios',
      pinterestUrl: '#',
      tiktokUrl: '#',
    },
  },
  'mrmarvis': {
    colors: {
      primaryText: '#071933',
      secondaryText: 'rgba(7, 25, 51, 0.7)',
      background: '#FFFFFF',
      border: '#E5E8EB',
      primaryGreen: '#03A458',
      secondaryGreen: '#CDEDDE',
      highlight: '#0000FF',
    },
    typography: {
      h1: {
        fontSize: '2rem',
        fontFamily: 'Figtree',
        fontWeight: 700,
        lineHeight: 1.3,
        letterSpacing: '0rem',
      },
      h2: {
        fontFamily: 'Figtree',
        fontWeight: 700,
      },
      h3: {
        fontFamily: 'Figtree',
        fontWeight: 640,
      },
      h4: {
        fontFamily: 'Figtree',
        fontWeight: 640,
      },
      h5: {
        fontSize: '2rem',
        fontFamily: 'Noto Serif Display',
        fontWeight: 400,
      },
      h6: {
        fontSize: '1.25rem',
        fontFamily: 'Figtree',
        fontWeight: 580,
        lineHeight: 1.3,
        letterSpacing: '0.0008rem',
      },
      body: {
        fontSize: '1rem',
        fontFamily: 'Figtree',
        fontWeight: 430,
      },
      'body-sm': {
        fontSize: '0.875rem',
        fontFamily: 'Figtree',
        fontWeight: 430,
        lineHeight: 1.5,
        letterSpacing: '0.002rem',
      },
      'body-xs': {
        fontSize: '0.75rem',
        fontFamily: 'Figtree',
        fontWeight: 430,
      },
    },
    spacing: {
      micro: '0.25rem',
      xs: '0.5rem',
      sm: '0.75rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2x': '3rem',
      '3x': '4.5rem',
    },
    borders: {
      radius: {
        sm: '0.375rem',
        md: '0.75rem',
        lg: '1.25rem',
      },
    },
    rounding: '6px',
    container: {
      maxWidth: '1200px',
    },
    sections: {
      showProductDetails: true,
      showPrimaryMenu: true,
      showSecondaryMenu: true,
      showImpact: true,
      showMaterials: true,
      showJourney: true,
      showSimilarProducts: true,
      showCTABanner: true,
    },
    images: {
      productImageZoom: 100,
      productImagePosition: 'center',
      carouselImageZoom: 100,
      carouselImagePosition: 'center',
    },
    branding: {
      headerLogoUrl: 'https://i.imgur.com/5h0kn61.png',
      bannerLogoUrl: '',
      bannerLogoHeight: 42,
    },
    menus: {
      primary: [
        { label: 'Care', url: 'https://www.mrmarvis.com/nl/care-guide?collection=c9d41806-cfee-40dc-86f1-55e9fce859af' },
        { label: 'Recycling', url: 'https://www.mrmarvis.com/nl/mr-marvis-x-sellpy' },
        { label: 'Exchange & Returns', url: 'https://www.mrmarvis.com/nl/exchanges-returns' },
      ],
      secondary: [
        { label: 'Our Purpose', url: 'https://www.mrmarvis.com/nl/our-purpose' },
        { label: 'Action Reports', url: 'https://www.mrmarvis.com/nl/action-report' },
        { label: 'Support', url: 'https://www.mrmarvis.com/nl/support' },
      ],
    },
    cta: {
      bannerBackgroundImage: 'https://cdn.mrmarvis.com/images/yb9xf4jc/production/0ea2184a9b494f8ab60d440f178de577589fa776-3900x1300.jpg',
      bannerCTAText: 'Shop nu',
      bannerCTAUrl: 'https://www.mrmarvis.com/nl/collections/easies',
      bannerCTABackgroundColor: '#FFFFFF',
      bannerCTATextColor: '#071933',
      bannerShowSubline: true,
      bannerSubline: 'Ontdek The Easies: de ultieme sweatpants',
    },
    social: {
      legalName: 'MR MARVIS Netherlands B.V.',
      showInstagram: true,
      showFacebook: true,
      showTwitter: false,
      showPinterest: false,
      showTiktok: true,
      useIcons: true,
      instagramUrl: 'https://www.instagram.com/mrmarvis',
      facebookUrl: 'https://www.facebook.com/MRMARVIS.official',
      twitterUrl: '',
      pinterestUrl: '',
      tiktokUrl: 'https://www.tiktok.com/@mrmarvis_',
    },
  },
  'luxora': {
    colors: {
      primaryText: '#1A1A1A',
      secondaryText: '#6B6B6B',
      background: '#FFFFFF',
      border: '#E0E0E0',
      primaryGreen: '#B8860B',
      secondaryGreen: '#F5E6D3',
      highlight: '#DAA520',
    },
    spacing: {
      micro: '0.1875rem',
      xs: '0.375rem',
      sm: '0.625rem',
      md: '0.875rem',
      lg: '1.25rem',
      xl: '1.75rem',
      '2x': '2.5rem',
      '3x': '3.75rem',
    },
    borders: {
      radius: {
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.5rem',
      },
    },
    container: {
      maxWidth: '1000px',
    },
    sections: {
      showProductDetails: true,
      showPrimaryMenu: true,
      showSecondaryMenu: true,
      showImpact: true,
      showMaterials: true,
      showJourney: true,
      showSimilarProducts: true,
      showCTABanner: true,
    },
    images: {
      productImageZoom: 95,
      productImagePosition: 'center',
      carouselImageZoom: 95,
      carouselImagePosition: 'center',
    },
    branding: {
      headerLogoUrl: 'https://res.cloudinary.com/dcdam15xy/image/upload/f_webp/v1746526939/aveleroApparelLogoBlack_iuhow7.png',
      bannerLogoUrl: 'https://res.cloudinary.com/dcdam15xy/image/upload/f_webp/v1746527118/aveleroApparelLogoWhite_b5drvc.png',
      bannerLogoHeight: 38,
    },
    menus: {
      primary: [
        { label: 'Fit Guide', url: '#size-guide' },
        { label: 'Styling Tips', url: '#styling' },
      ],
      secondary: [
        { label: 'Craftsmanship', url: '#craftsmanship' },
        { label: 'Sustainability', url: '#sustainability' },
        { label: 'Returns', url: '#returns' },
      ],
    },
    cta: {
      bannerBackgroundImage: 'https://res.cloudinary.com/dcdam15xy/image/upload/f_auto,q_auto/v1745934275/cta-banner-background_o3vjjw.jpg',
      bannerCTAText: 'VIEW MORE',
      bannerCTAUrl: 'https://example.com',
      bannerCTABackgroundColor: '#1A1A1A',
      bannerCTATextColor: '#FFFFFF',
      bannerShowSubline: false,
      bannerSubline: '',
    },
    social: {
      legalName: 'Luxora Fashion',
      showInstagram: true,
      showFacebook: false,
      showTwitter: true,
      showPinterest: true,
      showTiktok: true,
      useIcons: true,
      instagramUrl: 'https://instagram.com/luxorafashion',
      facebookUrl: '#',
      twitterUrl: 'https://twitter.com/luxorafashion',
      pinterestUrl: 'https://pinterest.com/luxorafashion',
      tiktokUrl: 'https://tiktok.com/@luxorafashion',
    },
  },
};


