-- ============================================================================
-- Product Exports Storage Bucket and RLS Policies
-- ============================================================================
-- This migration creates the product-exports storage bucket for storing
-- exported Excel files generated by the export feature.
--
-- Bucket configuration:
--   - Name: product-exports
--   - Public: false (private - requires authentication)
--   - File size limit: 100MB (104857600 bytes)
--   - Allowed MIME types: Excel only
--
-- Path structure: product-exports/{brand_id}/{export_job_id}/{filename}
-- ============================================================================

-- ============================================================================
-- 1. Create Bucket
-- ============================================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'product-exports',
  'product-exports',
  false,
  104857600, -- 100MB in bytes
  ARRAY['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- ============================================================================
-- 2. RLS Policies for product-exports bucket
-- ============================================================================

-- Allow brand members to read their export files
-- Path: product-exports/{brand_id}/{export_job_id}/{filename}
DROP POLICY IF EXISTS "Allow brand members read export files" ON storage.objects;
CREATE POLICY "Allow brand members read export files"
ON storage.objects FOR SELECT TO authenticated, service_role
USING ((bucket_id = 'product-exports') AND public.is_brand_member((path_tokens[1])::uuid));

-- Allow service role to upload export files (background job uses service role)
-- Note: Regular users don't upload directly - only the background job does
DROP POLICY IF EXISTS "Allow service role upload export files" ON storage.objects;
CREATE POLICY "Allow service role upload export files"
ON storage.objects FOR INSERT TO service_role
WITH CHECK (bucket_id = 'product-exports');

-- Allow brand owners to delete export files (cleanup)
DROP POLICY IF EXISTS "Allow brand owners delete export files" ON storage.objects;
CREATE POLICY "Allow brand owners delete export files"
ON storage.objects FOR DELETE TO authenticated, service_role
USING ((bucket_id = 'product-exports') AND public.is_brand_owner((path_tokens[1])::uuid));

-- Allow brand owners to update export files
DROP POLICY IF EXISTS "Allow brand owners update export files" ON storage.objects;
CREATE POLICY "Allow brand owners update export files"
ON storage.objects FOR UPDATE TO authenticated, service_role
USING ((bucket_id = 'product-exports') AND public.is_brand_owner((path_tokens[1])::uuid))
WITH CHECK ((bucket_id = 'product-exports') AND public.is_brand_owner((path_tokens[1])::uuid));

-- ============================================================================
-- Done
-- ============================================================================
SELECT 'Product exports storage bucket and policies created successfully' as message;
